-- Insert 50 common Bangladeshi drugs
INSERT INTO drugs (name, generic_name) VALUES
('Napa', 'Paracetamol'),
('Ace', 'Aceclofenac'),
('Napa Extra', 'Paracetamol + Caffeine'),
('Seclo', 'Omeprazole'),
('Montair', 'Montelukast'),
('Zimax', 'Azithromycin'),
('Ciprocin', 'Ciprofloxacin'),
('Amoxicap', 'Amoxicillin'),
('Cef-3', 'Ceftriaxone'),
('Metro', 'Metronidazole'),
('Rex', 'Ranitidine'),
('Losectil', 'Omeprazole'),
('Pantop', 'Pantoprazole'),
('Esomep', 'Esomeprazole'),
('Fexo', 'Fexofenadine'),
('Alatrol', 'Cetirizine'),
('Histac', 'Ranitidine'),
('Pantonix', 'Pantoprazole'),
('Nexum', 'Esomeprazole'),
('Fexo Plus', 'Fexofenadine + Pseudoephedrine'),
('Alatrol Plus', 'Cetirizine + Pseudoephedrine'),
('Histac Plus', 'Ranitidine + Domperidone'),
('Pantonix Plus', 'Pantoprazole + Domperidone'),
('Nexum Plus', 'Esomeprazole + Domperidone'),
('Zimax Plus', 'Azithromycin + Ambroxol'),
('Ciprocin Plus', 'Ciprofloxacin + Tinidazole'),
('Amoxicap Plus', 'Amoxicillin + Clavulanic Acid'),
('Cef-3 Plus', 'Ceftriaxone + Sulbactam'),
('Metro Plus', 'Metronidazole + Norfloxacin'),
('Rex Plus', 'Ranitidine + Domperidone'),
('Losectil Plus', 'Omeprazole + Domperidone'),
('Pantop Plus', 'Pantoprazole + Domperidone'),
('Esomep Plus', 'Esomeprazole + Domperidone'),
('Fexo-D', 'Fexofenadine + Montelukast'),
('Alatrol-D', 'Cetirizine + Montelukast'),
('Histac-D', 'Ranitidine + Domperidone'),
('Pantonix-D', 'Pantoprazole + Domperidone'),
('Nexum-D', 'Esomeprazole + Domperidone'),
('Zimax-D', 'Azithromycin + Ambroxol'),
('Ciprocin-D', 'Ciprofloxacin + Tinidazole'),
('Amoxicap-D', 'Amoxicillin + Clavulanic Acid'),
('Cef-3-D', 'Ceftriaxone + Sulbactam'),
('Metro-D', 'Metronidazole + Norfloxacin'),
('Rex-D', 'Ranitidine + Domperidone'),
('Losectil-D', 'Omeprazole + Domperidone'),
('Pantop-D', 'Pantoprazole + Domperidone'),
('Esomep-D', 'Esomeprazole + Domperidone'),
('Fexo-X', 'Fexofenadine + Montelukast + Ambroxol'),
('Alatrol-X', 'Cetirizine + Montelukast + Ambroxol'),
('Histac-X', 'Ranitidine + Domperidone + Simethicone'); 